name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Get last 1 commit messages
        id: get_commits
        run: echo "::set-output name=commits::$(git log -1 --pretty=format:'%h - %s')"

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Notify via Telegram
        run: |
          CHAT_IDS=${{ secrets.TELEGRAM_CHAT_IDS }}
          TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          MESSAGE="Деплой прошел успешно! 🎉<br/>Ссылка на бота: <a href=\"${{ secrets.TELEGRAM_BOT_LINK }}\">${{ secrets.TELEGRAM_BOT_LINK }}</a><br/><br/><b>Последние коммиты:</b><br/>${{ github.event.head_commit.message  }}"
          
          curl -X POST "https://api.telegram.org/bot${TOKEN}/sendMessage" \
            -H "Content-Type: application/json" \
            -d '{"chat_id": -1001824987291, "message_thread_id": 32053, "text": "'"${MESSAGE}"'", "parse_mode": "HTML" }'
          
